import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import SessionProvider from "@/utils/SessionProvider";
import { getServerSession } from "next-auth";
import { Container } from "@mui/material";
import StoreProvider from "./StoreProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Container>
            <SessionProvider session={session}>
              <Header />
              {children}
            </SessionProvider>
          </Container>
        </StoreProvider>
      </body>
    </html>
  );
}
