import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import "./globals.css";
import SessionProvider from "@/utils/SessionProvider";
import { getServerSession } from "next-auth";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <SessionProvider session={session}>
            <Header />
            {children}
          </SessionProvider>
        </Container>
      </body>
    </html>
  );
}
